name: CI

on:
  push:
    branches:
      - main
      - 'bitint-*'
  pull_request:
    branches:
      - main
      - 'bitint-*'
  schedule:
  - cron: '0 16 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Stable Build
      run: cargo +stable build --target-dir=target-stable --verbose
    - name: Nightly Build
      run: cargo +nightly build --target-dir=target-nightly --verbose
    - name: Run tests
      run: ./run-tests.sh
